// Actions in Card

export const LOAD_PEOPLE_SUCCESS = 'LOAD_PEOPLE_SUCCESS';
export const LOAD_ALLPEOPLE_SUCCESS = 'LOAD_ALLPEOPLE_SUCCESS';
export const LOAD_PLANETS_SUCCESS = 'LOAD_PLANETS_SUCCESS';
export const LOAD_PEOPLEFAVORITES_SUCCESS = 'LOAD_PEOPLEFAVORITES_SUCCESS';
export const UPDATE_PEOPLE_SUCCESS = 'UPDATE_PEOPLE_SUCCESS';